version: '2'

services:
  postgres:
    image: 'postgres:13.6-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '.:/app'
    env_file:
      - '.env'
    environment:
      POSTGRES_USER: ${DATABASE_DEV_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '8282:3000'
      - '1080:1080'
    volumes:
      - '.:/app'
      - docker_website_bash_history:/home/lumen/hist
    env_file:
      - '.env'
    environment:
      HISTFILE: /home/lumen/hist/.bash_history

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

  kibana:
    depends_on:
      - 'elasticsearch'
    image: kibana:7.17.0
    ports:
      - 5601:5601

  logstash:
    env_file:
      - '.env'
    depends_on:
      - 'elasticsearch'
    image: logstash:7.17.0
    command: logstash --path.settings /app/script/search_indexing/
    volumes:
      - '.:/app:ro'
      - logstash:/usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"

  redis:
    image: 'redis:7.2'
    command: redis-server
    volumes:
      - 'redis:/data'

volumes:
  postgres:
  esdata:
  logstash:
  docker_website_bash_history:
  redis:
